# Site settings
author: Blake Dalton
title: Discovering Data Science
header-img: img/home-bg.png
email: wblakedalton@gmail.com
copyright_name: Blake Dalton
description: > # this means to ignore newlines until "baseurl:"
  A Students Insight Into Learning Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wblakedalton

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
